### ISSUE TITLE
Mathematica 10?

### ISSUE THREAD

**Issue by DavidMStraub** [zbjornson/MYaml#1]
Thanks for this package, it works great with Mathematica 11.

In Mathematica 10, unfortunately it does not work. I believe the reason is that Mathematica 10 ships with a version 1.7.0 JRE, while your `yaml.jar` was compiled with 1.8.0. If this is correct, would it be possible for you to provide a backwards compatible version? Thanks!

**Comment by zbjornson** [comment]
Ah yeah, not a problem. Should be able to do today, thanks for reporting.

**Comment by zbjornson** [comment]
I think I did that correctly... can you give it a try please? Just re-run the [installation instructions from the readme](https://github.com/zbjornson/MYaml#installation).

**Comment by avelino3000** [comment]
I just tried the new version with Mathematica 10.4 and seems to work great. Thanks a lot!

**Comment by zbjornson** [comment]
Great, thanks!
